from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from src.utils.config import ensure_dir, load_config, write_text


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", default="configs/baselines.yaml")
    args = parser.parse_args()
    cfg = load_config(args.config)
    ensure_dir(cfg.get("output_dir", "results/baselines"))
    metrics_path = Path("tables/final_metrics.csv")
    if metrics_path.exists():
        frame = pd.read_csv(metrics_path)
        simple = frame[frame["model"].isin(["M0_ot_interpolation", "M1_intrinsic_neural"])]
        simple.to_csv(Path(cfg.get("output_dir", "results/baselines")) / "simple_baselines.csv", index=False)
    write_text(Path(cfg.get("output_dir", "results/baselines")) / "simple_baselines.md", "Simple interpolation and intrinsic neural baselines are generated by `src.train.train_model`.\n")
    print({"simple_baselines": "done"})


if __name__ == "__main__":
    main()

